name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: start build and push dist file to other repo.
    - uses: actions/checkout@master
    
    steps:
    - using: node12
    - run: src/main.js
